### ISSUE TITLE
xScheduledTask: Trigger has no option for Synchronize across time zones

### ISSUE THREAD

**Issue by StefanSchoof** [PowerShell/ComputerManagementDsc#109]
**Details of the scenario you tried and the problem that is occurring:**
I have some Scheduled Task set up with xScheduledTask in the Daylight Saving Time on a Windows Server 2016. After End of the DST my Jobs run one hour early. But one hour early the other system was not ready. After removing the "Synchronize across time zones" in the schedule, the start time is the current time (Local Non DST). 

I found no option to change the "Synchronize across time zones" this with xScheduledTask.

**Comment by PlagueHO** [comment]
Hi @StefanSchoof - are you able to tell me which version of xComputerManagement you're using? There was a fix in v3.0.0.0 that hopefully addressed this.

**Comment by StefanSchoof** [comment]
Currently I have 3.0.0.0. I do not remember updating the module since I set up my task, but It is possible I did.

**Comment by PlagueHO** [comment]
Are you able to take a look at the MOF file that was used to apply to the node to see if it used 3.0.0.0? If it is using 3.0.0.0 and the problem still exists then there may still be an issue with daylight savings time.

**Comment by StefanSchoof** [comment]
I search my log and found that the Install-Module run on the 06. October 2017 and the first apply failed because I used the old syntax. I had a `RepeatInterval = 1` which I removed. So I think I used 3.0.0.0 the whole time on this Server.

**Comment by PlagueHO** [comment]
This must still be an issue then. But you are right, it doesn't look like the `Synchronize across time zones` is exposed in the resource. I couldn't actually find this in the `New-ScheduledTaskTrigger` cmdlet either - so I'll need to do some more digging to see where/how this gets exposed to PowerShell.

**Comment by StefanSchoof** [comment]
Here a the steps for a repo:
 1. Create a Windows 2016 VM in Azure
 2. Deactivate the Hyper-V Time Synchronization Service
 3. Change Time Settings: Settings -> Time & language -> Set time automatically: Off, Time zone UTC + 01:00 Amsterdam, ..., Change Date to 27 October (Had DST Change on 29. October)
 5. Add a dsc file

```
configuration ScheduledTask
{
    param
    (
        [string[]]$NodeName = 'localhost'
    )

    Import-DSCResource -ModuleName xComputerManagement

    Node $NodeName
    {
        xScheduledTask Test
        {
            TaskName = "Test"
            ActionExecutable = "cmd"
            ScheduleType = "Daily"
            StartTime = "05:00:00 AM"
        }
    }
}
```

 6. `Install-Module xComputerManagement`
`. .\dsc.ps1`
`ScheduledTask`
`Start-DscConfiguration -Path .\ScheduledTask\ -Wait -Verbose`

 9. Take a look at the Task Scheduler
![task1](https://user-images.githubusercontent.com/4662023/32163401-78740e5c-bd5c-11e7-813f-b2cfe9c4ef01.PNG)
Next run time is at 5 AM

10. Change Time Back to 30. October

11. Take a lock again at the Task Scheduler
![task2](https://user-images.githubusercontent.com/4662023/32163433-952f4f5c-bd5c-11e7-9cb5-ed14cb1bd6db.PNG)
Next run time is at 4 AM

**Comment by hassan041** [comment]
Use Z at the end of time . it enables the option.
I have added Z at the end of the time, which does 2 things.

The time entries would be considered in UTC mode and it automatically converts to Local time in the server when the task is created.
it also enable option "Synchronize across time zones", which will take of any changes like daylight saving of the time zone

**Comment by PlagueHO** [comment]
Thanks @hassan041 - it is possible we'll be able to improve this code in the future.
