### ISSUE TITLE
Convert Module Name to ComputerManagementDsc

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/ComputerManagementDsc#119]
As per recent DSC Resource Naming guidelines changes:
https://github.com/PowerShell/DscResources/blob/master/Naming.md

This should also include merging of SystemLocaleDsc and TimezoneDsc

**Comment by timhaintz** [comment]
@PlagueHO if we get StorageDsc sorted out, happy to do this one next. 
Looks to be a couple of extra steps with incorporating SystemLocaleDsc, TimezoneDsc and LanguageDsc Modules. Happy to help out though.
Thanks, Tim.

**Comment by PlagueHO** [comment]
Hi @timhaintz - would definitely appreciate the help! But I've actually already done this one - I'm just waiting till after the next resource kit release to merge it (as I wanted some bug fixes to go out to xComputerManagement before we rename it).

But I've got other ones that haven't been done if you want to have at it :grin: xCertificate and xDFS. 

I'm working on xNetworking rename, but I want to complete the conversion to HQRM on that one before renaming (which takes quite a bit of time).

Your help is really great and very much appreciated! 🏆

**Comment by timhaintz** [comment]
Cool, no worries. Are xCertificate and xDFS good to go from an HQRM perspective? Will have a go at them this week. 👍 . Thanks.

**Comment by PlagueHO** [comment]
Yep! xDFS and xCertificate are both HQRM already (the only one that I maintain that isn't HQRM is xNetworking because it has so many resources in it).
