### ISSUE TITLE
xComputer:  JoinOU property failing to take PowerShell Expression

### ISSUE THREAD

**Issue by seanbruck** [PowerShell/ComputerManagementDsc#131]
OS:  Win 2012 R2
PowerShell on Node:  5.1
xComputer version:  3.1

Configuration below works except for the JoinOU.  It ignores the value of the registry path provided, and instead adds the computer object into the default container:  CN=Computers,DC=nfcu,DC=net

xComputer JoinDomain
        {
            Name       = 'localhost'
            DomainName = $StandardComputerDomain
            Credential = $Credential
            JoinOU     = ((Get-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\OUInformation -ErrorAction SilentlyContinue).TargetPathOU)
        }

**Comment by PlagueHO** [comment]
Hi @seanbruck!

Can you confirm that the TargetPathOU value of the registry path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\OUInformation exists on the machine **compiling** the MOF? If this value is not set on the machine the MOF is compiled on it will be empty in the MOF and therefore the target node will not apply it.

But if this is not the case then I'll look into this further! Thanks for raising this BTW.

**Comment by seanbruck** [comment]
Hi PlagueHO, we may have a chicken and egg.  This is Azure DSC, so the compilation is being done on the Azure host, prior to the endpoint node ever seeing the configuration.

**Comment by PlagueHO** [comment]
Hi @seanbruck - ah, I see. So is there anywhere else you can get the path to the OU that you want the computer object to be created in? An automation variable of some kind?

**Comment by seanbruck** [comment]
Unfortunately no, the value of the OU is determined at runtime based on current configurations on the target node.  From what you're describing, the compilation job will always calculate the value of the reg key "too soon" when using Azure PowerShell DSC.

**Comment by PlagueHO** [comment]
Hi @seanbruck - so there is no way the OU can be set in the VM at the time of first boot to allow it to be consumed in the DSC compile process? 

At what point is the HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\OUInformation TargetPathOU registry key set on the VM? Or is it never set at all?
