### ISSUE TITLE
xScheduledTask space in taskpath causes failure

### ISSUE THREAD

**Issue by ryancbutler** [PowerShell/ComputerManagementDsc#153]
Windows 10 Enterprise
xComputerManagement: 4.1.0.0 

I'm trying to disable the below task but doesn't seem to like the space in the task path. Get the following error.  Any task without a space works just fine.
```
The parameter is incorrect.
    + CategoryInfo          : InvalidArgument: (PS_ScheduledTask:) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070057,Register-ScheduledTask
    + PSComputerName        : LOCALHOST
```
My configuration is as follows
```
configuration DisableService {

    Import-DscResource -ModuleName PsDesiredStateConfiguration
    Import-DscResource -ModuleName xComputerManagement
node LOCALHOST {

xScheduledTask "Microsoft Compatibility Appraiser"
    {
    TaskName = "Microsoft Compatibility Appraiser"
    TaskPath = '\Microsoft\Windows\Application Experience\'
    Enable   = $false
    }
}

}
DisableService
Start-DscConfiguration .\DisableService\ -wait -force -verbose
```

**Comment by johlju** [comment]
Could you provide the verbose logs? It is easier to follow whats happening in the verbose logs.

**Comment by chrisshearing** [comment]
Hi,

I'm also having this issue - noticed it with the same built-in windows task, 

I'm using ComputerManagementDsc  6.3.0.0

The output from the command is as follows:

`
PS C:\WINDOWS\system32> configuration DisableService {
>>
>>     Import-DscResource -ModuleName PsDesiredStateConfiguration
>>     Import-DscResource -ModuleName ComputerManagementDSC
>> node LOCALHOST {
>>
>> ScheduledTask "Microsoft Compatibility Appraiser"
>>     {
>>     TaskName = "Microsoft Compatibility Appraiser"
>>     TaskPath = '\Microsoft\Windows\Application Experience\'
>>     Enable   = $false
>>     }
>> }
>>
>> }
>> DisableService
>> Start-DscConfiguration .\DisableService\ -wait -force -verbose


    Directory: C:\WINDOWS\system32\DisableService


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       05/04/2019     15:32           2118 LOCALHOST.mof
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer RES-MDT-W10-3 with user sid
S-1-5-21-583907252-1500820517-725345543-1170.
VERBOSE: [RES-MDT-W10-3]: LCM:  [ Start  Set      ]
VERBOSE: [RES-MDT-W10-3]: LCM:  [ Start  Resource ]  [[ScheduledTask]Microsoft Compatibility Appraiser]
VERBOSE: [RES-MDT-W10-3]: LCM:  [ Start  Test     ]  [[ScheduledTask]Microsoft Compatibility Appraiser]
VERBOSE: [RES-MDT-W10-3]:                            [[ScheduledTask]Microsoft Compatibility Appraiser] Testing
scheduled task 'Microsoft Compatibility Appraiser' in '\Microsoft\Windows\Application Experience\'.
VERBOSE: [RES-MDT-W10-3]:                            [[ScheduledTask]Microsoft Compatibility Appraiser] Getting
scheduled task 'Microsoft Compatibility Appraiser' in '\Microsoft\Windows\Application Experience\'.
VERBOSE: [RES-MDT-W10-3]:                            [[ScheduledTask]Microsoft Compatibility Appraiser] Task 'Microsoft
 Compatibility Appraiser' found in '\Microsoft\Windows\Application Experience\'. Retrieving settings, first action,
first trigger and repetition settings.
VERBOSE: [RES-MDT-W10-3]:                            [[ScheduledTask]Microsoft Compatibility Appraiser] Detected
schedule type 'Once' for first trigger.
VERBOSE: [RES-MDT-W10-3]:                            [[ScheduledTask]Microsoft Compatibility Appraiser] Current
scheduled task values retrieved.
VERBOSE: [RES-MDT-W10-3]:                            [[ScheduledTask]Microsoft Compatibility Appraiser] Testing DSC
parameter state.
VERBOSE: [RES-MDT-W10-3]: LCM:  [ End    Test     ]  [[ScheduledTask]Microsoft Compatibility Appraiser]  in 2.2260
seconds.
VERBOSE: [RES-MDT-W10-3]: LCM:  [ Start  Set      ]  [[ScheduledTask]Microsoft Compatibility Appraiser]
VERBOSE: [RES-MDT-W10-3]:                            [[ScheduledTask]Microsoft Compatibility Appraiser] Setting
scheduled task 'Microsoft Compatibility Appraiser' in '\Microsoft\Windows\Application Experience\'.
VERBOSE: [RES-MDT-W10-3]:                            [[ScheduledTask]Microsoft Compatibility Appraiser] Getting
scheduled task 'Microsoft Compatibility Appraiser' in '\Microsoft\Windows\Application Experience\'.
VERBOSE: [RES-MDT-W10-3]:                            [[ScheduledTask]Microsoft Compatibility Appraiser] Task 'Microsoft
 Compatibility Appraiser' found in '\Microsoft\Windows\Application Experience\'. Retrieving settings, first action,
first trigger and repetition settings.
VERBOSE: [RES-MDT-W10-3]:                            [[ScheduledTask]Microsoft Compatibility Appraiser] Detected
schedule type 'Once' for first trigger.
VERBOSE: [RES-MDT-W10-3]:                            [[ScheduledTask]Microsoft Compatibility Appraiser] Disabling
existing scheduled task 'Microsoft Compatibility Appraiser' in '\Microsoft\Windows\Application Experience\'.
The parameter is incorrect.
    + CategoryInfo          : InvalidArgument: (PS_ScheduledTask:) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070057,Register-ScheduledTask
    + PSComputerName        : LOCALHOST

VERBOSE: [RES-MDT-W10-3]: LCM:  [ End    Set      ]  [[ScheduledTask]Microsoft Compatibility Appraiser]  in 2.2290
seconds.
The PowerShell DSC resource '[ScheduledTask]Microsoft Compatibility Appraiser' with SourceInfo '::7::1::ScheduledTask'
threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged
to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : LOCALHOST

VERBOSE: [RES-MDT-W10-3]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : LOCALHOST

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 6.751 seconds

`

If you need anything else to help diagnose this issue, please let me know

**Comment by chrisshearing** [comment]
It looks like the following function is called in the module DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1

```
function Disable-ScheduledTask
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory = $true)]
        [System.String]
        $TaskName,

        [Parameter()]
        [System.String]
        $TaskPath = '\'
    )

    $existingTask = Get-ScheduledTask @PSBoundParameters
    $existingTask.Settings.Enabled = $false
    $null = $existingTask | Register-ScheduledTask @PSBoundParameters -Force
}
```

The error is generated by the line

```
    $null = $existingTask | Register-ScheduledTask @PSBoundParameters -Force
```

I can get it to repeat the error straight in powershell by running the commands manually.

I'm wondering if this function is a legacy fix of some sort? As Disable-ScheduledTask exists as a function already

https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/disable-scheduledtask?view=win10-ps

and this version works if called on the task containing spaces

```
Get-ScheduledTask -TaskName "Microsoft Compatibility Appraiser" -TaskPath "\Microsoft\Windows\Application Experience\" | Disable-ScheduledTask
```

**Comment by chrisshearing** [comment]
Actually, it seems to straight up work with the Disable-ScheduledTask function, without piping from a Get, I must have had a syntax error when I was testing.

```
Disable-ScheduledTask -TaskName "Microsoft Compatibility Appraiser" -TaskPath "\Microsoft\Windows\Application Experience\"
```

This is the exact same format as the helper function in DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1:953

```
        {
            Write-Verbose -Message ($script:localizedData.DisablingExistingScheduledTask -f $TaskName, $TaskPath)
            Disable-ScheduledTask -TaskName $TaskName -TaskPath $TaskPath

            return
        }
```

So I tried just deleting the Disable-ScheduledTask function present in that file, and it used the built in Powershell command and worked.

I'm afraid I don't know the purpose or history of that function, so I can't say why it's needed, but it works  with scheduled tasks containing spaces it the name without it.
