### ISSUE TITLE
xPowerPlan: Trying to use it on Windows 10 fails with no Activate method error

### ISSUE THREAD

**Issue by MarkKharitonov** [PowerShell/ComputerManagementDsc#155]
Please, observe the following code:
```
$Name = "High Performance"
$getCimInstanceArguments = @{
    Name   = 'root\cimv2\power'
    Class  = 'Win32_PowerPlan'
    Filter = "ElementName = '$Name'"
}
$plan = Get-CimInstance @getCimInstanceArguments
$plan | Invoke-CimMethod -MethodName Activate
```
It works on Windows Server 2012, but fails with no Activate method when ran on Windows 10. Amazingly it works on Windows 8.

Hence the xPowerPlan resource cannot be used on Windows 10.

**Comment by mrkrch** [comment]
I can confirm.

However, the problem is not with PowerShell. Somewhere between 1703 to 1709, the Win32_PowerPlan class's "Activate" method was broken. It seemed to coincide with the new "Windows performance power slider" feature.

**Comment by johlju** [comment]
As per previous comment I will label this as 'bug' and 'external'.

**Comment by chrdionne** [comment]
I have same issue in Windows Server 1803.
