### ISSUE TITLE
Computer: add parameter to define the domain controller when joining

### ISSUE THREAD

**Issue by r3dlin3** [PowerShell/ComputerManagementDsc#161]
**Details of the scenario you tried and the problem that is occurring:**
It is not possible to define the domain controller a computer will use to join.
In some specific scenario (implying network filtering), it is mandatory to define the server.
The PowerShell cmdlet `Add-Computer` has a `server` parameter that can be leveraged.

**The DSC configuration that is using the resource (as detailed as possible):**
Computer

**Version of the Operating System and PowerShell the DSC Target Node is running:**
All Windows

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
5.0.0

**Comment by johlju** [comment]
Sounds like a good addition to the resource. Labeling this as help wanted so that anyone in the community can run with it.
