### ISSUE TITLE
TimeZone not an available resource?

### ISSUE THREAD

**Issue by jfletcher93** [PowerShell/ComputerManagementDsc#163]
The dsc resouce for TimeZone is not available since installing the module? any idea why this is?

**Comment by johlju** [comment]
It was recently migrated into ComputerManagementDsc from xTimeZone. Around mid June there will be a new release of ComputerManagementDsc which will contain TimeZone. Until then you have to use xTimeZone or use the Dev-branch of ComputerManagementDsc.

**Comment by jfletcher93** [comment]
Ahh! I see, apologies was under the impression the current module contained it. Shall await the new release then! Thanks for your response!

**Comment by johlju** [comment]
Reopening this, and we will close it as soon as we have release next release.

**Comment by PlagueHO** [comment]
We have the next release so I'm closing this.
