### ISSUE TITLE
ScheduledTask: Add support to trigger on an event

### ISSUE THREAD

**Issue by danielboth** [PowerShell/ComputerManagementDsc#167]
**Details of the scenario:**
A scheduled task can be setup to trigger on an event happening in an eventlog. Currently, the ScheduledTask DSC resource allows setting up triggers based on: 

Once
Daily
Weekly
AtStartup
AtLogOn

It would be nice to add another ScheduledType here, which we could name "OnEvent" to allow scheduled tasks triggering on an event.

Under the hood, this will mean setting up an eventlog subscription in XML, validating that subscription and then setting up a scheduled task trigger (MSFT_TaskEventTrigger). In the TaskEventTrigger the XML needs to be converted to string to save it as a subscription.

**Comment by johlju** [comment]
Sounds like a good enhancement. Are you seeing MSFT_TaskEventTrigger as a sub class to the MSFT_ScheduledTask class (a property in MSFT_ScheduledTask  using an embedded instance sub class) , or a separate resource?

**Comment by danielboth** [comment]
All the current triggers are embedded in this resource, so I think it makes sense to do the same for the OnEvent trigger here. So let's keep it in the ScheduledTask resource instead of creating a separate one.

**Comment by PlagueHO** [comment]
Cool! This would be an awesome addition! 👍

**Comment by danielboth** [comment]
Hi @PlagueHO, I created PR #169 to implement this, it's waiting on a review, would be great if you have some time for that.
