### ISSUE TITLE
ScheduledTask: Using ScheduledTask resource to create task that recurs once every month on the 1st?

### ISSUE THREAD

**Issue by grpowershell** [PowerShell/ComputerManagementDsc#173]
So I want to have DSC create a scheduled task on a target computer where the task recurs every month on a certain date (in my case, the 1st of the month) but it doesn't appear possible to specify a date for a task to start. 

Any feedback/insight would be appreciated.

**Comment by grpowershell** [comment]
Now obviously a way around this is to create a schedule task that runs every day that runs a script that works out if it's the 1st of the month and then executes whatever you want it to execute. Perfectly possible but I would have thought given that a standard Windows scheduled task has monthly functionality that it should be incorporated in to this DSC resource.

**Comment by johlju** [comment]
If you can create what you looking for with `New-ScheduledTaskTrigger` cmdlet then we could match that with the parameters available, and see if there are any functionality that is missing.
