### ISSUE TITLE
Timezone: Wiki

### ISSUE THREAD

**Issue by OffColour** [PowerShell/ComputerManagementDsc#177]
I made some changes to the Wiki earlier to reflect that Timezone is now included.
I've now just seen in a PR that the Wiki is auto-generated. As Timezone was added three months ago, is it missing the necessary documentation or was the push to the Wiki not competed after the last build?

**Comment by PlagueHO** [comment]
Hi There @OffColour - thank you for picking this up and reporting it. I've updated the documentation from the last push to master (https://ci.appveyor.com/project/PowerShell/computermanagementdsc/build/1.9.73.0/artifacts). We've been planning to automate this process, but haven't had time to complete it yet.

I'll close this issue now.
