### ISSUE TITLE
ScheduledTask RepetitionDuration 1 day or 24:00:00

### ISSUE THREAD

**Issue by johnm1191** [PowerShell/ComputerManagementDsc#183]
I was attempting to create tasks with a duration of 24:00:00 but while the configuration compiles, it is output to task scheduler as 24.00:00:00, or 24 days. Is this the intended functionality of the TimeSpan conversion? Is there a plan to support custom values like '1 day' similar to indefinitely?

This is running on a 2012 R2 Datacenter machine running PowerShell version 5.1 and ComputerManagementDsc version 5.2.0.0

**Comment by johlju** [comment]
Maybe `24:00:00` doesn't work, maybe it needs to be `'23:59:59'`. since `00:00:00` probably indicate midnight?
Maybe you can write `'1.00:00:00'` for one day?

I'm guessing here. 🙂
