### ISSUE TITLE
ScheduledTask: IdleWaitTimeout returned from Get-TargetResource always null

### ISSUE THREAD

**Issue by djwork** [PowerShell/ComputerManagementDsc#186]
Background: Working on a fork to implement run as NETWORK SERVICE and I was getting Test-TargetResource invalidly returning false. Traced it to this issue among others. 

The bug is caused by the following line in Get-TargetResource:
`IdleWaitTimeout                 = ConvertTo-TimeSpanStringFromScheduledTaskString -TimeSpan $settings.IdleSettings.IdleWaitTimeout`
The problem is IdleSettings object does not have a IdleWaitTimeout property, but it does have a WaitTimeout property.

I have implemented a fix in my fork, creating this issue to reference in CHANGELOG.md

**Comment by djwork** [comment]
See my pull request:
https://github.com/PowerShell/ComputerManagementDsc/pull/187

**Comment by PlagueHO** [comment]
Thank you @djwork - look forward to merging this. Will review once the merge conflicts are sorted.

**Comment by djwork** [comment]
@PlagueHO I rebased off of the dev branch, not sure if I did it correctly, I am a git novice

**Comment by djwork** [comment]
New pull request:
https://github.com/PowerShell/ComputerManagementDsc/pull/192

**Comment by djwork** [comment]
The fix has been merged into the dev branch and is awaiting release
