### ISSUE TITLE
PowerShellModule: New resource proposal

### ISSUE THREAD

**Issue by johlju** [PowerShell/ComputerManagementDsc#205]
### Description
A resource that can install and uninstall a PowerShell module.

I initially thought of this module to be dedicated to install the SqlServer PowerShell module from PowerShell Gallery (see issue https://github.com/PowerShell/SqlServerDsc/issues/540). But after thinking about this now, I thought this might be useful in other scenarios. 

### Proposed properties
```
[ClassVersion("1.0.0.0"), FriendlyName("PowerShellModule")]
class MSFT_PowerShellModule : OMI_BaseResource
{
    [Key, Description("The name of the PowerShell module to install or uninstall.")] String Path;
    [Write, Description("If the PowerShell module should be present on absent on the server being configured."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("An UNC path from where to copy the module. If not set the module will be downloaded from PowerShell gallery.")] String Path;
    [Write, Description("If set to a registered repository the module will be downloaded from that repository. If not set, then the module will be downloaded from PowerShell Gallery. If parameter Path is set, this parameter will be ignored.")] String Repository;
    [Write, Description("If this is set to $true and the same version already exists on the computer, then the downloaded module will be overwrite the existing module.")] Boolean Force;
    [Write, Description("The version of the PowerShell modul that must be used, if the version does not exists, and cannot be copied or downloaded, the resource will throw an error.")] Boolean RequiredVersion;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("The credentials used to access the path set in the parameter Path. This is ignored if downloading the PowerShell module from a repository. This is also optional if either the SYSTEM account or if the built-in PsDcsRunAsCredential is used and has access to the path set in the parameter Path.")] String SourceCredential;
};
```

### Special considerations or limitations
Not sure if we should add the parameter `SourceCredential`, but instead assume that `PsDcsRunAsCredential` is used.

**Comment by PlagueHO** [comment]
Isn't there already a module for this hosted as part of the PowerShellGet repo? https://github.com/PowerShell/PowerShellGet/tree/development/PowerShellGet/DSCResources/MSFT_PSModule

It isn't quite up to the standards of the resource kit though.

So it might be still worth building a better one?

**Comment by johlju** [comment]
I did not know that there was plans to add resources to that module! It was added very recently too. Feels wrong to invent the wheel again, might be better to extend that resource in the PowerShellGet repo with proper tests, but looking at the appveyor.yml that could be tricky since PowerShellGet is tested on a couple of different WMF versions (and PS Core). Adding our test framework should be possible, of course, but will need to modify PowerShellGet's test framework, or start the testing of the DSC resource in a different job. The later would be best I think.

Maybe we should await the release of the PSModule resource to see what we do?

**Comment by johlju** [comment]
I fixed tests using DscResource.Tests test framework and pushed them to PR https://github.com/PowerShell/PowerShellGet/pull/413. I will push integration tests shortly.

If the module is not published with PowerShellGet, we can just move the entire thing here and build from there. 🤔

**Comment by PlagueHO** [comment]
@johlju - Shall we close this one one that your awesome improvements have gone into PowerShellGet? :grin:

**Comment by johlju** [comment]
Yes, I think we can. :smile: If for any reason that module is not released we can reopen this. :)
