### ISSUE TITLE
ComputerManagementDsc Nuget Spec during testing

### ISSUE THREAD

**Issue by djwork** [PowerShell/ComputerManagementDsc#213]
As part developing the fix issue #130 I have been running the appveyor build/unit test for my fork. When appveyor runs it generates a sample nuget file. I loaded the file into an internal repository where I store development modules and then tried to install the module via the PackageManagement cmdlets. 

But PackageManagement did not recognize the nuget file as a valid PS Module, when comparing the my nuget package with the latest release ComputerManagementDsc.6.2.0.0.nupkg from PS Gallery I notice the where a lot of differences, specifically:

- from my nuget: <tags>DesiredStateConfiguration DSC DSCResourceKit</tags>
- from the release nuget: <tags>DesiredStateConfiguration DSC DSCResourceKit DSCResource PSModule PSIncludes_DscResource PSDscResource_Computer PSDscResource_OfflineDomainJoin PSDscResource_PowerPlan PSDscResource_PowerShellExecutionPolicy PSDscResource_ScheduledTask PSDscResource_TimeZone PSDscResource_VirtualMemory PSDscResource_WindowsEventLog</tags>

When I manually synced the tags from the release nuget into my nuget, PackageManagement recognized the nuget file as a valid PS Module and installed it.

So any clues how I can get appveyor to correctly generate the nuget spec on my fork during development and testing?

Thanks
Daniel Work

**Comment by PlagueHO** [comment]
Thanks for raising this @djwork . The release process that the DSC team uses when they releases the modules to the PS Gallery is actually a different process and doesn't use the Nuget package produced as part of the AppVeyor build.

That said, the Nuget Package that is produced should still match what is produced by the DSC team and should still be a valid package.

This package is actually produced by the (DscResource.Tests)[https://github.com/PowerShell/DscResource.Tests]
 AppVeyor.psm1 module. Are you able to raise this request over there?

**Comment by djwork** [comment]
@PlagueHO 
Little bit confused, I can see reference to "DscResource.Tests\AppVeyor.psm1" in ComputerManagementDsc's appveyor.yml
`Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"`

So are you saying:

1. I should raise an issue on PowerShell/DscResource.Tests asking them to make changes to the generation of nuget packages via AppVeyor?
2. Or PowerShell/DscResource.Tests can advise us how to update ComputerManagementDsc's appveyor.yml to correct the nuget packages generated via AppVeyor?

**Comment by PlagueHO** [comment]
The first one. I'm a maintainer over there so I can take a look at the issue and see if I can sort it out (when I have the time) or one of the other maintainers might take a look.

But essentially, all the CI code is inside the AppVeyor.psm1 over there, so anything that occurs in AppVeyor is controlled by that repo - which is why raising the issue over there makes the most sense.

**Comment by djwork** [comment]
Moved to [DscResource.Tests #318](https://github.com/PowerShell/DscResource.Tests/issues/318)
