### ISSUE TITLE
RemoteDesktopAdmin: New resource proposal

### ISSUE THREAD

**Issue by X-Guardian** [PowerShell/ComputerManagementDsc#224]
### Description

There is currently a separate DSC module [xRemoteDesktopAdmin](https://github.com/PowerShell/xRemoteDesktopAdmin) which contains a single resource for configuring 'Remote Desktop for Administration' on a Windows server, along with the RDP Authentication security. The resource code for this hasn't been touched for 4 years and has outstanding bugs, and also needs making `SingleInstance`. I started to submit PRs to bring the module up to HQRM standards and fix the bugs, but then though that perhaps rather than having a separate module for one simple resource, it would be better integrated into the `ComputerManagementDsc` module.
I've already re-written the resource to HQRM standards along with Pester tests.

### Proposed properties

```
[ClassVersion("1.0.0.0"), FriendlyName("RemoteDesktopAdmin")]
class MSFT_RemoteDesktopAdmin : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Required, Description("Determines whether or not the computer should accept remote desktop connections.  Present sets the value to Enabled and Absent sets the value to Disabled."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("User Authentication.  Setting this value to Secure configures the machine to require Network Level Authentication (NLA)."), ValueMap{"Secure","NonSecure"}, Values{"Secure","NonSecure"}] String UserAuthentication;
};
```

### Special considerations or limitations

None

**Comment by PlagueHO** [comment]
Hi @X-Guardian - sounds like a good idea. I'm in agreement that bringing it into this module makes sense - especially if you've done the HQRM work already.

**Comment by X-Guardian** [comment]
Cheers @PlagueHO, I'll raise a PR for this.
