### ISSUE TITLE
WindowsCapability and WindowsCapabilitySet: New Resource(s) Proposal

### ISSUE THREAD

**Issue by aydeisen** [PowerShell/ComputerManagementDsc#241]
### Description
A DSC Module around the WindowsCapability cmdlets to manage the enabled and disabled capabilities.  It should work similarly to the WindowsOptionalFeature and WindowsOptionalFeatureSet DSC Resources

### Proposed properties
Name (Key)
LogLevel
LogPath
NoWindowsUpdateCheck (mapped to the `LimitAccess` parameter)
DependsOn
Ensure

### Special considerations or limitations
Originally filed by @mgreenegit in PowerShell/PSDscResources#168.  The discussion in that issue was to include it into ComputerManagementDsc

When executing `Get-WindowsCapability`, the convention for the name is that it ends with three tildes followed by the version number.  It would be great if the DSC Resource only required the name, and not the tildes and version number (or, at the very least, make the tildes and everything to the right of them optional)

**Comment by PlagueHO** [comment]
Thanks for raising this @aydeisen - sounds like a great addition to me. Parameters look good (DependsOn does not need to be specifically included in the resource as is always included).

**Comment by Outek** [comment]
Ok, i started with this, because i need it for myself 😁

**Comment by PlagueHO** [comment]
Awesome! Thanks @Outek

**Comment by PlagueHO** [comment]
@Outek, this just came up at the DSC Community call - lots of eagerness to get this one through to enable installation of SSH-Server :grin: @mgreenegit has offered assistance if required. I'm happy to help too. We'll aim to fast track this one.

**Comment by Outek** [comment]
@PlagueHO  Alright, what should i do, just send the PR?

**Comment by PlagueHO** [comment]
@Outek - yep, if it is ready?

**Comment by PlagueHO** [comment]
Thanks @mgreenegit - @Outek has submitted the PR has been: #263. The review is under way, but definitely take a look at ensure the functionality/MOF is going to support requirements. We can extend for future versions - just aiming to get an MVP out before release this week.

**Comment by PlagueHO** [comment]
This has now been merged @mgreenegit - ready for next release! Thanks @Outek for your work in getting this through.
