### ISSUE TITLE
ScheduledTask: Get-ScheduledTask function name clash with Carbon module

### ISSUE THREAD

**Issue by bozho** [PowerShell/ComputerManagementDsc#248]
#### Details of the scenario you tried and the problem that is occurring
We're using DSC resources from both ComputerManagementDsc and Carbon modules.

Carbon implements `Get-ScheduledTask` function, which is missing the `-TaskPath` parameter. Functions from `ScheduledTask` DSC resource call `Get-ScheduledTask` without importing `ScheduledTasks` modules, or calling the function using the module name (i.e. `ScheduledTasks\Get-ScheduledTask`)

This makes it impossible to use or even have installed both modules on the same machine.

#### Suggested solution to the issue
While this issue might be better addressed in Carbon, it doesn't really hurt making `ScheduledTask` code more specific about which `Get-ScheduledTask` function it's using.

We could either make the code explicitly import the `ScheduledTasks` module, or use the "long" form to call overlapping functions (I *think* it's just `Get-ScheduledTask, but I can review)

I'd be happy to submit a patch.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running

```


OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.3024.amd64fre.rs1_release.190530-2002
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running

```

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.2969                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.2969                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
`6.5.0.0`

**Comment by PlagueHO** [comment]
Hi @bozho - thanks for raising this. Would be happy to accept a PR with the change of adding the module name to the function name call (e.g. `ScheduledTasks\Get-ScheduledTask`).
