### ISSUE TITLE
ScheduledTask: Type mismatch with MultipleInstances option

### ISSUE THREAD

**Issue by bozho** [PowerShell/ComputerManagementDsc#255]
#### Details of the scenario you tried and the problem that is occurring
`MultipleInstances` option is a `String`. However, `Get-TargetResource` returns it as `Microsoft.PowerShell.Cmdletization.GeneratedTypes.ScheduledTask.MultipleInstancesEnum`, which causes `Test-TargetResource` function to always return `$false`.

#### Verbose logs showing the problem
```
VERBOSE: [TEST-SERVER]:                            [[ScheduledTask]MyScheduledTask] NOTMATCH: Type mismatch for property 'MultipleInstances' Current state type is                                            'Microsoft.PowerShell.Cmdletization.GeneratedTypes.ScheduledTask.MultipleInstancesEnum' and desired type is 'System.String'.                                                                                                                              
```

#### Suggested solution to the issue
`Test-TargetResource` could convert `$currentValues['MultipleInstances']` value from enum to `String`

Alternatively, `Get-TargetResource` could do the enum -> string conversion.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
`6.5.0.0`

**Comment by PlagueHO** [comment]
This is easier to do now that this has been refactored. I'd suggest casting at this line: https://github.com/PowerShell/ComputerManagementDsc/blob/dev/DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1#L1816

**Comment by bozho** [comment]
I agree. I'll submit the patch during the day.
