### ISSUE TITLE
TimeZone Module is missing

### ISSUE THREAD

**Issue by Gill-Bates** [PowerShell/ComputerManagementDsc#257]
In the PS Gallery (Modules) ComputerManagementDSC offers the Module TimeZone

![grafik](https://user-images.githubusercontent.com/25774289/64337820-6d024500-cfe0-11e9-989e-123c4a12713d.png)
After importing it, TimeZone is missing

![grafik](https://user-images.githubusercontent.com/25774289/64337838-7be8f780-cfe0-11e9-9e1c-e8724d4fb4cd.png)

![grafik](https://user-images.githubusercontent.com/25774289/64337855-83100580-cfe0-11e9-998b-ca8a08ee5316.png)

My DSC Agent crashs due to the fact, that TimeZone is not recognized. Any ideas how to solve this?

**Comment by PlagueHO** [comment]
Hi @Gill-Bates - that is a strange one. Are there any logs that are produced?

**Comment by Gill-Bates** [comment]
Solved that issue. When a new automation account is created inside Azure Portal, the default Module Version is 5.0.

First step is to override the old version by importing the new version from the Gallery to 6.5. it seems to do this step twice until TimeZone appears inside the available modules.

Since TimeZone pops up, my DSC confit works fine. This issue can be closed.

But the behavior of Azure is still weired...

**Comment by PlagueHO** [comment]
That is strange about the selection of 5.0 as the version. Thanks for posting about the behavior. Definitely seems strange and worth looking into further.
