### ISSUE TITLE
The RemoteDesktopAdmin, PendingReboot and SMBShare Resources are missing from the Wiki Documentation

### ISSUE THREAD

**Issue by X-Guardian** [PowerShell/ComputerManagementDsc#268]
The auto-generated markdown files for these resources are in the following Appveyor build artifact from the 7.0.0 release. Can someone upload them to the Wiki?

https://ci.appveyor.com/api/buildjobs/k1s5t27vtyd836oc/artifacts/ComputerManagementDsc_1.9.398.0_wikicontent.zip

**Comment by PlagueHO** [comment]
Thanks for the reminder @X-Guardian - will do tonight

**Comment by PlagueHO** [comment]
I have updated these. Once moved over to DSCCommunity.org we can automate this.

**Comment by X-Guardian** [comment]
Hi @PlagueHO, can you add `SMBShare' to the `_SIDEBAR` file?

**Comment by PlagueHO** [comment]
Done - sorry I missed this!

**Comment by X-Guardian** [comment]
np. It will be much better when we can automate this.

**Comment by PlagueHO** [comment]
Yah - hopefully not too much longer. Gael just working out the finer details of the process of migration. They wanted to do some testing first.
