### ISSUE TITLE
The 'ComputerManagementDsc.psd1' Description Property is Out-Of-Date

### ISSUE THREAD

**Issue by X-Guardian** [PowerShell/ComputerManagementDsc#269]
This description ends up as the module description on the [PowerShell Gallery](https://www.powershellgallery.com/packages/ComputerManagementDsc/7.0.0.0)

Current text:

"The ComputerManagementDsc module is originally part of the Windows PowerShell Desired StateConfiguration (DSC) Resource Kit. This version has been modified for use in Azure. This module contains the xComputer and xDisk resources. These DSC Resources allow you to perform computer management tasks, like joining a domain or initializing disks.
All of the resources in the DSC Resource Kit are provided AS IS, and are not supported through any Microsoft standard support program or service."

How about changing it to something like:

"The ComputerManagementDsc module contains DSC resources for configuration of a Windows computer. These DSC resources allow you to perform computer management tasks, like joining a domain or initializing disks.
All of the resources in the DSC Resource Kit are provided AS IS, and are not supported through any Microsoft standard support program or service."

**Comment by PlagueHO** [comment]
Thanks @X-Guardian - good catch. And that is really out of date!
