### ISSUE TITLE
Remote Desktop Session limits: New resource proposal

### ISSUE THREAD

**Issue by fullenw1** [PowerShell/ComputerManagementDsc#271]
### Description
Currently we can manage remote desktop sessions with GPO under **Machine\Windows Components\Remote Desktop Services\Remote Desktop Session Host\Session Time Limits**
### Proposed properties
**MaxDisconnectionTime** ==> Set time limit for disconnected sessions
HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\MaxDisconnectionTime
DWord (Milliseconds)

**MaxIdleTime** ==> Set time limit for active but idle Remote Desktop Services sessions
HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\MaxIdleTime
DWord (Milliseconds)

**MaxConnectionTime** ==> Set time limit for active Remote Desktop Services sessions
HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\MaxConnectionTime
DWord (Milliseconds)

**fResetBroken** ==> End session when time limits are reached
HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\fResetBroken
DWord 0|1 False|True

**Comment by raandree** [comment]
Isn't it OK using the 'xRegsitry' resource and set the registry values accordingly? If you use Datum and the concept described in the [DscWorkshop](https://github.com/AutomatedLab/DscWorkshop/), you can put these values into the configuration (composite resource) that you use to configure Remote Desktop Services or put the values into some baseline layer.

**Comment by fullenw1** [comment]
Hi Raimund!

Interesting question...
There is a **RemoteDesktopAdmin** resource too in this module, though this can be managed with registry values only.

I tend to configure everything with DSC modules and propose new resources when I have to use registry values (I have already 33 registry values in my DSC configuration beside the DSC resource settings).
My DSC configuration seems better organized by resources, more readable and better maintainable when I walk through my configuration by DSC modules/resources than looking at my long list of DSC registry values even with Datum.

In the same way, we could create GPO configurations with only registry objects...

Also, I thought that one day DSC would catch up most of the GPO settings...

I am pretty new to DSC configurations. So maybe my reasoning is wrong...
And I also understand that human resources are limited and that some requests have a higher priority.
Thus I wouldn't mind if you postpone this request or just close it :-)

**Comment by fullenw1** [comment]
Just found an existing resource for that :-)

https://github.com/PowerShell/xRemoteDesktopSessionHost
