### ISSUE TITLE
Service: New Resource Proposal

### ISSUE THREAD

**Issue by 1800Zeta** [PowerShell/ComputerManagementDsc#275]
### Description
Resource for configuring a Windows service

### Proposed properties
Name - Mandatory
Display Name
Description
Startup Type
Status

### Special considerations or limitations
Would use Get-Service, Set-Service, Start-Service, Stop-Service. Main goal for this is to disable the Spooler Service. Am happy to take this on. I did have a look through and didn't spot anything

**Comment by PlagueHO** [comment]
Hi @1800Zeta - this resource already exists over in https://github.com/PowerShell/xPSDesiredStateConfiguration and also https://github.com/PowerShell/PSDscResources.

It is also in the inbox PSDesiredStateConfiguration resources :grin:

**Comment by 1800Zeta** [comment]
Doh! Sorry, never mind. Won't do it then. Thanks for the heads up :D

**Comment by PlagueHO** [comment]
No worries @1800Zeta  :grin:
