### ISSUE TITLE
MSFT_xPowerPlan Support for Nano server

### ISSUE THREAD

**Issue by AndreasSobczyk** [PowerShell/ComputerManagementDsc#65]
MSFT_xPowerPlan support for Nano server is currently missing.
There is already a module available that does this and it could easily be merged 
https://github.com/J0F3/cPowerPlan

If nobody else is working on it i will properly take a look at how it could be done.

**Comment by PlagueHO** [comment]
Hi @AndreasSobczyk - sorry for not getting back to you sooner (I've only just picked up this repo as one of the ones I maintain so I'm trying to clear the backlog)!

This would be awesome if you feel like merging the nano support across - it would gratefully accepted. So if you're keen on doing this, I'll mark the issue as in progress.

**Comment by AndreasSobczyk** [comment]
Hi @PlagueHO -  no problem, i actually forgot this completely since Microsoft have chosen to remove the support for intrastructure roles in Nano server, and my usecase was for hyper-v
